# Site settings
title: "sandw1ch"
description: "Sandw1ch's Personal Blog."
baseurl: ""
url: "https://sandw1.ch"
title_description: "My name is sandw1ch and I hack things."
title_image: "https://i.pinimg.com/originals/51/41/2d/51412d5c4c9e4bb481282795c49fa160.png"
github_repository: https://github.com/sebrink/blog
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _sandw1ch
github_username:  sebrink
linkedin_link: https://www.linkedin.com/in/scott-brink-981b7b104/

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;sebrink&gt; on <a href=\"https://github.com/sebrink\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
